name: app

type: 'php:8.4'

dependencies:
    php:
        composer/composer: "^2"

mounts:
  'web/uploads':
    source: local
    source_path: uploads

disk: 2048

relationships:
    postgresql: 'postgresql:postgresql'

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash

    deploy: |
        set -x -e

        symfony-deploy