name: is-here

type: 'php:8.4'

dependencies:
  php:
    composer/composer: "^2"

runtime:
    extensions:
        - apcu
        - ctype
        - iconv
        - mbstring
        - pdo_pgsql
        - sodium
        - xsl

mounts:
  'var':
    source: local
    source_path: var
  'web/uploads':
    source: local
    source_path: uploads

disk: 2048

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"
        "/build": { root: "public/build", expires: 365d }
        "/assets/controllers": { root: "public/assets/controllers", expires: 365d }

relationships:
    database: 'postgresql:postgresql'

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash

    deploy: |
        set -x -e

        symfony-deploy